### ISSUE TITLE
[Suggestion] Make symmetry plane easier to find

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1028] opened 2018-12-05 23:50 UTC
### Short Description of the issue:

So I started reworking this ship but I can't find where the symmetry plane starts and as such, I can't really move it. Also getting it to centre in the middle of a block can sometimes be fairly tough

![image](https://user-images.githubusercontent.com/43644633/49551781-8a3aa380-f8e8-11e8-81b6-054724bb54ca.png)

**Comment by ZachZent** [comment] 2018-12-06 08:07
Also it's been said before, but we need multiple planes. Even the way it was before with just one mirror for X, Y, and Z though being able to have multiple lines of symmetry for each axis would be a nice bonus.

As for the viability, that has been a problem with much of the game's interfaces, codex, and so on. That is simply because the translucent light blue matches too well with the rest of the game like the rings and the blueish-black of the space. Glass blocks for example are almost invisible in the hotbar

**Comment by JRL101** [comment] 2018-12-06 18:35
Im having problems just using symmetry.The red bot refuses to copy some times, if you put down a new ship it doesnt place a block so you cant start a ship and then if you have the symmetry red bot on and press F5 to remove the yellow the red one hangs around still linked to the ghost ship doing nothing.

I also find im constantly moving the symmetry plane around my accident. Maybe have a "move symmetry plane" option in the bot.

I would LOVE having multiple mirror planes on the same axis. That would be cool for things that were symmetrical but on different sides of the ship.

**Comment by tsunamayo** [comment] 2018-12-12 08:12
Okay it seems it need a big rework. There is an option to hide the plane, did you guys made sure it was active? Also you can active it to not move it by accident. I am thinking of maybe have another way to place as it seems confusing. 
Also for the multiple plane on the same axis it dont really make sense as it, as it is a path to infinite blocks haha (I did it in the past).

**Comment by ZachZent** [comment] 2018-12-12 08:41
The first issue with symmetry is the red drone randomly starts spinning and stops placing. You can  "reactivate" the drone by moving the ship slightly which will cause it to place all the blocks at once

As for the making the mirror plane invisible, I'd say instead make it so the drone option is to **lock** the mirror. That way you can see it at all times without accidentally moving it. Personally I wouldn't mind a block, but I know that is against the idea of simplifying the codex. So I will suggest with the drone, there are three options: Mirror X, Mirror Y, and Mirror Z. When you "activate" each, the plane will come up in that direction. You can move it like you can now. Then in the drone interface, you click lock. Maybe it changes the texture or something. The plane is translucent enough so it being up at all times won't be an issue in building. Oh, and the X, Y and Z would have different color (RGB?)

For the infinite block thing, yea I can see how that can be an issue. As long as you can (eventually) place mirrors in different planes at the same time (x, y, and z) it will be good enough. A copy paste system would easily replace the need for multiple planes on the same... plane

**Comment by JRL101** [comment] 2018-12-12 08:42
You can also reset the mirror drone by turning symmetry off and on again

**Comment by gmunga5** [comment] 2018-12-18 04:00
I had the plane visible when I was doing this I think, the issue is that there is no way to tell if it is viewable or not unless you know where it is. In the case of this example I was actually unable to find where the plane was without placing blocks and gradually working my way to mirror line.

**Comment by tsunamayo** [comment] 2019-09-20 05:01
This issue should be fixed with the new workflow. You need to simply equip the tool to see the plane. Thanks!

**Closed by tsunamayo** 2019-09-20 05:01 UTC
Labels: Bug
