### ISSUE TITLE
Removing seat glitches player into the ground

### ISSUE THREAD

**Issue by AUTplayed** [tsunamayo/Skywanderers#573] opened 2018-03-08 00:57 UTC
As you can see in the video, removing a seat glitches the player into the ground far away.

https://i.imgur.com/CVsRbbE.mp4

**Comment by CyaNox** [comment] 2018-03-08 09:16
Possibly a duplicate of #570 or perhaps a regression? What version are you experiencing this in?

**Comment by AUTplayed** [comment] 2018-03-08 13:04
18w09b

**Comment by tsunamayo** [comment] 2018-03-12 02:01
Hi, yes it was a duplicate and the fix is live now, thanks for reporting that @AUTplayed. @CyaNox glad to see you, hope you are doing good! Cheers

**Closed by tsunamayo** 2018-03-12 02:01 UTC
Labels: Bug, Duplicate
