### ISSUE TITLE
[EXPERIMENTAL] Passing over geometry with the Multi-place causes placement issues

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#373] opened 2017-11-05 00:49 UTC
Before
![image](https://user-images.githubusercontent.com/33023316/32410876-124df15e-c1c3-11e7-8af0-5294b2d0aa28.png)

After
![image](https://user-images.githubusercontent.com/33023316/32410877-1b3195d2-c1c3-11e7-8174-3bebf7366099.png)

**Comment by tsunamayo** [comment] 2017-11-05 01:26
Sorry I am having a hard time to understand the picture, it seems that whole flat plane is in fact a slope right? And the slope on the front is in fact a flat plane? Also I cant reproduce, not sure what I am doing wrong.

**Comment by Napther** [comment] 2017-11-05 12:45
The hull of the ship comprises of the Tilled Hull and their wedges. The little "hooks" that Im attaching the Orange spaced armour to are made from the second type of Hull, the same type as the Orange going down.

The hooks comprise of a dark grey wedge on the top that is being dragged over by the Orange wedges.
The Orange wedges then seem to overwrite their colour onto these grey wedges.

That little black Tilled Wedge near to the cluster of ships in the background is a result of a similar issue, where I dragged the Spaced orange wedges into the hull by accident. Pressing Undo seems to cause that wedge it passed through to delete itself afterwards.

Sorry for not being so clear the first time, wrote this late in the night whilst sick, heh.

**Comment by tsunamayo** [comment] 2017-11-06 00:54
Hum I dont reproduce this issue, on my side the first block retains their color. I reproduce the undo issue though. Is it something you manage to reproduce 100% of the time? Thanks

**Comment by Napther** [comment] 2017-11-10 12:37
@tsunamayo Sadly Ive been unable to reproduce except this very specific case. Ill send you the BP file momentarily:

[Multiplace Issue ExampleBP.zip](https://github.com/tsunamayo/Skywanderers/files/1461320/Multiplace.Issue.ExampleBP.zip)

It has mirror mode on currently. Placing like I did in the images at the start (Next to the Yellow hull pieces) should yield the same results.

Both aspects of this bug (Colour change and deleting blocks that have been passed through by the multi place on an Undo) are still present in 17w45b (I think this is the current one.)

**Comment by tsunamayo** [comment] 2017-11-14 02:55
Okay it is actually linked to the mirroring. I am keeping you posted, thanks for the bp.

**Comment by tsunamayo** [comment] 2017-11-14 03:00
It is fixed now! Cheers

**Closed by tsunamayo** 2017-11-14 03:00 UTC
Labels: Bug, Medium
