### ISSUE TITLE
All blocks are invisible

### ISSUE THREAD

**Issue by Xxxsquidlover101xxX** [tsunamayo/Skywanderers#1146] opened 2019-05-31 11:30 UTC
I saw all my blocks invisible, deleted all my save files, reinstalled the game and they're still invisible, when i try to delete or place a new one in a grid they become visible for a tiny instance, just enough to notice it but not to see the object

https://cdn.discordapp.com/attachments/416013956331601930/583972937745432576/unknown.png

**Comment by Xxxsquidlover101xxX** [comment] 2019-05-31 11:35
i don't really know how to reproduce though, as it happens on anything  i try to build

**Comment by tsunamayo** [comment] 2019-05-31 11:46
Okay, sorry to hear that, So could you please send me your output.log.
Also could you press F3, then click on "EnableOcclusion" (so it become unitcked), and tell if you see something. Thanks!

**Comment by MormegiI** [comment] 2019-06-01 01:07
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243239/output_log.txt)
Since i have the same problem I thought I can contribute here... Even registered here :D
Deactivating Occlusion makes the things visible.

**Comment by tsunamayo** [comment] 2019-06-01 01:17
Hi, thanks for the feedback. So could one of you send me his blueprint file?
You can zip the folder 
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data
And send it to me, I will know what use to test. Thanks!

**Comment by MormegiI** [comment] 2019-06-01 13:54
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/3243814/Save_Data.zip)
There you are. Good luck!

**Comment by tsunamayo** [comment] 2019-06-02 00:47
Okay nothing wrong with the save, I can see them without any issue. Do you confirm you have this issue with the latest build? Thanks

**Comment by MormegiI** [comment] 2019-06-02 00:53
As long as the "Enable Occlusion" is active, no blocks are visible. At least no player created blocks. The Ice rings are visible. If I turn off Enable Occlusion, everything is visible. Hope that helps

**Comment by tsunamayo** [comment] 2019-06-04 07:26
@Xxxsquidlover101xxX could you please tell me your GFX card model, and send me an output.log? Thanks!

**Comment by OldIronsides** [comment] 2019-06-04 18:10
I also have this same issue

The game looks fine, no lag or anything, but any blocks I try to place are invisible, they flash visible for a split second when adding a new block to the whole, and I can see the outlines when hovering the cursor on them, but nothing I do turns them visible.
 
Skywanderers version: 19w23a 
Graphics Card: GTX 765M

**Comment by tsunamayo** [comment] 2019-06-05 06:32
Hello gentlemen @OldIronsides , @MormegiI @Xxxsquidlover101xxX , I want to confirm the issue is indeed occlusion culling. Could you please do a test for me?
Unzip the build called  Raster Occlusion Testing.zip on my dropbox at:
https://www.dropbox.com/s/hdukzc4lastx57n/Raster%20Occlusion%20Testing.zip?dl=0

Then run it and tell what you see:
 - center red sphere
 - transparent cube
 - sphere inside the transparent cubes.

This will be useful to get this issue fixed with Unity.
Thanks!

**Comment by tsunamayo** [comment] 2019-06-09 22:27
@OldIronsides @MormegiI 
Okay guys, so there is a new patch 19w23d that should have fixed the issue. Thanks for your patience! Cheers

**Closed by tsunamayo** 2019-06-09 22:27 UTC
Labels: Bug

**Comment by Xxxsquidlover101xxX** [comment] 2019-06-24 13:04
Yep that’s the issue, I just confirmed it

 

 

De: Francois Duret [mailto:notifications@github.com] 
Enviado el: miércoles, 5 de junio de 2019 8:33
Para: tsunamayo/Skywanderers
CC: MrSquid; Mention
Asunto: Re: [tsunamayo/Skywanderers] All blocks are invisible (#1146)

 

Hello gentlemen @OldIronsides <https://github.com/OldIronsides>  , @MormegiI <https://github.com/MormegiI>  @Xxxsquidlover101xxX <https://github.com/Xxxsquidlover101xxX>  , I want to confirm the issue is indeed occlusion culling. Could you please do a test for me?
Unzip the build called Raster Occlusion Testing.zip on my dropbox at:
https://www.dropbox.com/s/hdukzc4lastx57n/Raster%20Occlusion%20Testing.zip?dl=0

Then run it and tell what you see:

*	center red sphere
*	transparent cube
*	sphere inside the transparent cubes.

This will be useful to get this issue fixed with Unity.
Thanks!

**Comment by Xxxsquidlover101xxX** [comment] 2019-06-24 13:07
Managed to solve it, it turns out you need to press F3 and disable occlusion

 

 

De: OldIronsides [mailto:notifications@github.com] 
Enviado el: martes, 4 de junio de 2019 20:10
Para: tsunamayo/Skywanderers
CC: MrSquid; Mention
Asunto: Re: [tsunamayo/Skywanderers] All blocks are invisible (#1146)

 

I also have this same issue

The game looks fine, no lag or anything, but any blocks I try to place are invisible, they flash visible for a split second when adding a new block to the whole, and I can see the outlines when hovering the cursor on them, but nothing I do turns them visible.

Skywanderers version: 19w23a
Graphics Card: GTX 765M
