### ISSUE TITLE
[19w24a] bricks built on sliders stay arranged according to parent grid

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Skywanderers#1310] opened 2019-07-04 13:36 UTC
### Short Description of the issue:

Sliders have a minimal height; Once you place a brick on them, it'll be slightly higher than the parent object - BUT! Try to keep building; Any brick you'd add from the sides will be offset height-wise, following the parent object's grid instead of the child's. Building on top (opposit side of the slider) forces bricks to be in the correct place.

### Steps to reproduce the issue:

1-Place a slider anywhere

2-Place some bricks on top of the moving part.

3-Try to add more bricks to the sides of the bricks you built in step 2.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: 

### Additional information:

https://cdn.discordapp.com/attachments/416013956331601930/596333368530960404/20190703223001_1.jpg

**Comment by tsunamayo** [comment] 2019-07-06 02:48
Hi, okay actually it is not a bug, the brick grid is supposed to work like that. If you use small plate and build on top of them you will get the same issue.
Not sure if this something I should try to address or not, I will think about it, but I agree it can be confusing. 
Thanks

**Comment by tsunamayo** [comment] 2019-07-09 06:56
Okay actually with the new grid offset feature this will work as you expect. Feature will be in upcoming 19w28b patch. Cheers!

**Closed by tsunamayo** 2019-07-09 06:56 UTC
Labels: Bug
