### ISSUE TITLE
[Experimental] First Freeform Block cannot be interacted with

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#669] opened 2018-03-28 17:02 UTC
Hi!

For some reason, the first freeform block set on an entity can not be interacted with at all, no highlight, no customization and no destruction. Also, the player can freely move through the FFB.

![12](https://user-images.githubusercontent.com/33256107/38044927-6d056ef6-32bb-11e8-8095-f7468acc0a38.gif)

As you can see, when aiming at the first FFB of that entity, the highlighted block is the starter block.

**Comment by Napther** [comment] 2018-03-28 22:07
Duplicate of #654

**Closed** 2018-03-29 01:44 UTC
Labels: Bug, Duplicate
