### ISSUE TITLE
Unable to Pause Game in Cockpit/Seat

### ISSUE THREAD

**Issue by DarianLStephens** [tsunamayo/Skywanderers#179] opened 2017-10-25 11:02 UTC
As the title says, you don't seem to be able to enter any kind of menu while sitting.
I've tried the build menu, pausing, and even alt+tabbing, but I couldn't seem to do anything that wasn't cockpit-related while sitting.
I could still access buttons and leave the seat, but it was frustrating for a few moments.
I don't think the pause menu should be restricted at any time, or it's just frustrating when you can't respond to that email or check that thing outside of the game without getting another window on top of it with frantic alt-tabbing, leaving the seat (Which isn't always feasible depending on the craft and speed), or opening the Steam Overlay.

**Comment by tsunamayo** [comment] 2017-10-26 04:56
duplicate of #99 . Thanks

**Closed by tsunamayo** 2017-10-26 04:56 UTC
Labels: Suggestion
