### ISSUE TITLE
Bug: Game shows a potential for mirroring child entities [Experimental]

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#798] opened 2018-05-13 20:42 UTC
So I stumbled upon a very intriguing "bug" while working a build. As you can see in the picture I'm aiming to break a single brick and the game is showing me on the mirrored side that it -could- delete the exact mirrored brick that is on a different entity. I wasn't sure if this is something secret you're working on or if it's just a bug that could potentially be useful.

Re-logging fixes that but I also wasn't seeing that preview until after having the game open for some time. It's happened for me a few times now but I'm just now reporting it. I've also talked to a few others that have seen this sort of thing happening.

I know many of us have been expressing a desire for child entity mirroring and I got too hyped to not report this 😂 

- Skywanderers version: 18w19a
- Graphics Card: Nvidia GTX 970

![20180513152215_1](https://user-images.githubusercontent.com/32974671/39971632-13dabf52-56c4-11e8-8da5-334685e7c462.png)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1998906/output_log.txt)

**Comment by tsunamayo** [comment] 2018-05-20 02:50
Hi, no it is an issue linked to the way the shader displays the region to be deleted, but it should have been fixed... I will re-investigate the issue. Cheers

**Comment by tsunamayo** [comment] 2018-06-04 00:40
Hi, I am not able to reproduce, is there any thing special you are doing?
How where spawned the child entity (rotor, hinge, did you used blueprint copy?)
Also can you reproduce an all the brick or just this one?
If you had the blueprint that could help!
Thanks

**Comment by tsunamayo** [comment] 2019-07-09 07:43
This issue should be fixed now. Thanks!

**Closed by tsunamayo** 2019-07-09 07:43 UTC
Labels: Bug
