### ISSUE TITLE
[BUG] Right Clicking Only Gives Output of -1

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#583] opened 2018-03-13 18:55 UTC
Unlike before where right-clicking toggled buttons, lights, and mirror blocks, now it will only turn stuff off/output -1. For example, if you right-click a mirror block, you can turn it off, but not turn it on again.

**Comment by Sullos** [comment] 2018-03-14 06:16
Also the same as my post #571 :)

**Comment by CyaNox** [comment] 2018-03-14 14:30
Duplicate of #571.

**Closed by CyaNox** 2018-03-14 14:30 UTC
Labels: Duplicate
