### ISSUE TITLE
[19w40b] Shield capacity loss on reload

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1479] opened 2019-10-11 05:58 UTC
### Short Description of the issue:
When placing shields, the total shield value for the system is listed as one value initially, but after saving and reloading, it changes to a lower value.

### Steps to reproduce the issue:
Place shields on a ship, link shield blocks to screen to view ship shield stats, save and reload.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Before save&reload:
![20191011005341_1](https://user-images.githubusercontent.com/33041786/66627646-01545e80-ebc2-11e9-87b6-d0aedd354ef8.jpg)

After save&reload:
![20191011005516_1](https://user-images.githubusercontent.com/33041786/66627642-fe596e00-ebc1-11e9-8cc8-5b22c0c3daaf.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3715832/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment] 2019-10-11 06:11
Did some more testing. I removed all capacitors from the setup and using only generators, and after save/reloading the screen showed no information at all this time. Using the link tool showed that it was impossible to unlink the screen from to the generator it had originally been connected to; the generator could not be selected for linking anymore. Mousing over this generator also showed that the tooltip information displayed for it did not match its real stats, such as physical dimensions. I'm including the blueprint in case it's useful.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3715857/output_log.txt)

[Shield Bug Test Blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/3715858/Shield.Bug.Test.Blueprint.zip)

![20191011010347_1](https://user-images.githubusercontent.com/33041786/66628166-9e63c700-ebc3-11e9-8821-68741a2823e3.jpg)


![20191011010549_1](https://user-images.githubusercontent.com/33041786/66628158-973cb900-ebc3-11e9-9bfe-bc00126b9c49.jpg)

**Comment by tsunamayo** [comment] 2019-10-16 00:41
Okay I have fix the capacitor loading issue, fix will be in 19w42a. Not sure for the screen link issue though, I cant reproduce it and cant find the shield on your ship...
Thanks!

**Closed** 2019-10-24 06:56 UTC
Labels: Bug
