### ISSUE TITLE
Hotkeys all share the same assignment. Changing one changes them all.

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1278] opened 2019-06-15 21:14 UTC
Hotkeys that are assigned a key force all other hotkeys to have that same assignment.
...
Place 2 hotkeys connected to a yoke.
Open the hotkey GUI of both to check assignment.
Change the assigned key of one of the hotkeys.
Look in the GUI of the hotkey you did not change the assignment of.
...
- Skywanderers version: 19w24a
- Graphics Card: Nvidia GeForce GTX 1060 6gb
...
issue #869 might be related.
...
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3293554/output_log.txt)

**Comment by tsunamayo** [comment] 2019-06-21 05:49
The issue is fixed in upcoming 19w25a. Actually it was an UI issue. Thanks!

**Closed by tsunamayo** 2019-06-21 05:49 UTC
Labels: Bug
