### ISSUE TITLE
[17w47a2] light sources not emitting light on children

### ISSUE THREAD

**Issue by EthanNar** [tsunamayo/Skywanderers#474] opened 2017-11-22 21:39 UTC
Have a wall on a hinge, lights on the wall, light's not emitting.
![20171122153716_1](https://user-images.githubusercontent.com/7775562/33150911-4abf74c8-cf9b-11e7-855b-728bf97a15aa.jpg)

Toggling on and back off does not fix the issue.

**Comment by CyaNox** [comment] 2017-11-22 23:00
Duplicate of #460.

**Closed by CyaNox** 2017-11-22 23:00 UTC
Labels: Duplicate
