### ISSUE TITLE
Entering pilot mode makes wierd constant clicking noise.

### ISSUE THREAD

**Issue by Varraka** [tsunamayo/Skywanderers#612] opened 2018-03-23 13:46 UTC
Hoyz, just getting started, found some bugs, worst of witch is this robotic drunken cricket noise every time i enter a entity to pilot. The sound is verry loud but if I hit f4 and zoom away it gets quiet but yet still present.  The noise went away once out of about 10 sessions, when i piloted the blue fighter to the asteroid belt in the dead space inbetween. While flying to the belt at full speed, the graphics on the thrust would duplicate, then speed off to the top left of the screen making it look like i fired wierd missiles, this seemed periodic and only happened once every few mins while attempting to reach the belt. Also noticed my custom character options are not saving period. Then my game state as well would not save untill i left the planet ring. Custom control menu slider bugged out a few times and would not let me to top option. 1st time bug reporter so bare with me >< , should different issues be in different threads?
 System requirement info: Also dropping my system specs because on post install graphic options, the game was to laggy to enjoy. If i decreased res to 1280 x 1024 it got smooth, OR if i take off v-sync and the other 2 graphic options at max res it gets alot better.
Intel I5 cpu @3.20 ghz
Ram 8gb
Gforce Gt 720 2gb ddr3
64 bits
Windows 7
Direct x 11
(it might be older than some players but shes a fine robot)  XD  
Searched sys specs for this game and found thread where you didnt know, so hope that helps. What sys spec`s are you aiming for?

**Comment by Varraka** [comment] 2018-03-24 15:56
Found a few more last night while working on a small 10m rowboat. The game saved the progress of my project when exiting directly to desktop. When I exited to main menue then exit to desktop, it seems i lost few hrs of work and reverted back to last "save state".  Is there a way to save a blueprint, found the identity block but no save to hardrive option. Strange orange-red lazer looking graphic encirled the system after exiting the identity block. Symatry block turns off but not back on again.   Also noticed when deleting chairs while building it would zoom my toon over to the main ship core inside the blocks of the ship.  (scotty`s drunk at the teleporter again) :D

**Comment by Varraka** [comment] 2018-03-25 22:09
Ah so this newbie found f1 is save game for any yall that didnt know. I assumed bad that exiting would prompt a save feature, and i dont think it does. Hope this helps someone. Exiting from game to main menu then re-entering game freezes the client it seems. Sorry bout this 1st thread, too messy with multiple bugs, i`ll keep posts to 1 bug limit from now on! XD

**Comment by tsunamayo** [comment] 2018-03-26 03:44
Hi, thanks for report that many bugs! Sorry to asking, but could you please book a single issue per thread? That way I can ask for more info if needed, close the issue when resolved, ect. It will makes my life easier for tracking. Thanks!

**Comment by Varraka** [comment] 2018-03-26 04:37
Yes, no problem at all. Sorry about that! XD

**Comment by tsunamayo** [comment] 2018-03-28 07:57
Hi, to come back on the weird noise, in which ship does it happens? There is a sound effect for the spaceship thruster, is that or something different? Cheers

**Comment by Varraka** [comment] 2018-03-28 15:18
Ok ive been toying around with this bug and have been able to reproduce it
using the vid screen block. At first i thought it was entering ships but i
was incorect, it was just that the pre-builds i entered all had vid
screens. Working the rowboat ive been able to pilot fine without the
noise.. Then i added a vid screen so the toon rowing could see in front of
them and it happenend. I can actually place a vid screen anywhere, not link
it to anything, then produce the bug by entering. It happens when the
screen is linked to, as mentioned while entering the pre-build. It sounds
to me like a loop check is making a switch noise. The sound dissapates the
further I get away from the screen so its definately coming from that. The
pre-build blue fighter and the large black mech is where i noticed it
first. Hope this helps!

**Comment by tsunamayo** [comment] 2018-03-29 05:52
I am still unable to reproduce, the blue fighter have to screen built on, what did you build exactly? Like what kind of assignment did you made? Could you please send your output.log file? Thanks

**Comment by Varraka** [comment] 2018-03-29 17:59
Ok test results are in with evidence, here goes. Simple setup. 4x4 screen.
Linked Switch to Screen, then Screen to Camera. Clicked switch, screen
stays blank. Click into screen, go into camera view with constant clicking
noise. Before clicking screen:


After clicking (f key) screen when clicking noise is present:


As you can see, the screen does not turn on but I enter it looking at
myself. The noise is verry fast like on a .1 sec loop.

 Then i found another glitch that must be related. Adding logic as the
activator like this:



 Did this:

 If you look closely im running around way in the background there. XD
In this version of the glitch, no annoying noise, but i was not able to
exit this mode and had to exit game to correct it.  I figure i`d keep the
setup simple to find the core root, plus ive blown up the blue fighter in
my game testing "other things". ><
When I find the log Ill send it too.

**Closed** 2019-08-06 05:05 UTC
Labels: Bug
