### ISSUE TITLE
Hyperspeed Makes things go woggy or disables mouse control

### ISSUE THREAD

**Issue by Jdman6** [tsunamayo/Skywanderers#863] opened 2018-06-07 11:45 UTC
### Short Description of the issue:
When I activate hyperspeed there is a 50/50 chance it will either start this weird graphics bug that continues after I stop or it will not allow steering the ship via mouse control while at hperspeed. Mouse control comes back after I drop out of hyperspeed but the graphics bug continues until I restart the program
...

### Steps to reproduce the issue: 18w20a
Just entering hyperspeed, though it seems to make the graphics bug more likely if one sits in the seat while the mouse bug is more likely if one is not sitting in the seat.
...

### Environment
- Skywanderers version: 
- Graphics Card: Nvidia GeForce 840M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20180607121638_1](https://user-images.githubusercontent.com/40027280/41097404-12829222-6a58-11e8-974f-c57d4a9e42c6.jpg)
![20180607121648_1](https://user-images.githubusercontent.com/40027280/41097408-16acfa4a-6a58-11e8-9fc0-d28936ff97d2.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2080233/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment] 2018-06-11 17:05
I've encountered this bug as well. On my end, it seems to be caused by moving away from the location you entered the ship at -- this movement can be by hyperspeed, or it can be by Boost, or just using the WASD keys. It occurs regardless of the method of traveling used. The further you get from that point, the worse the wobbling becomes.

Exiting the ship fully and re-entering it resets the bug so that there's no wobbling. Moving from that new point starts the wobbling again. So basically, the wobbling increases the further you get from where you entered the ship.

I've been using the joystick, so I can't tell if the mouse has been bugging out. Joystick control seems to work fine while this bug is happening.

**Comment by tsunamayo** [comment] 2019-06-21 07:10
Okay issue is fixed in 19w25a. Thanks for spotting that one! Cheers

**Closed by tsunamayo** 2019-06-21 07:10 UTC
Labels: Bug
