### ISSUE TITLE
Bug  -  Symmetry painting not consistently working

### ISSUE THREAD

**Issue by ttmm3** [tsunamayo/Skywanderers#501] opened 2017-12-02 18:09 UTC
https://gfycat.com/gifs/detail/TameReliableAardwolf

Brand new symmetry block and all, the painting works occasionally, but not always.  Running the latest stable build

**Comment by Sullos** [comment] 2017-12-03 07:06
I too have been having this problem.
Till it’s fixed I just suggest selecting the colour using right click, first. Then place the blocks of that colour, it’s tedious, but guarantees correct colour blocks on all axis of symmetry.

**Comment by JRL101** [comment] 2017-12-03 10:36
Confirmed, Mirror seems to be skipping blocks/bricks.
Mirror also seems to be placing bricks and block in the same space in some cases. But no texture clipping is visible, they just become impossible to paint until one is deleted.

**Comment by tsunamayo** [comment] 2017-12-03 12:07
Hi, this issues is now fixed. Thanks!

**Closed by tsunamayo** 2017-12-03 12:07 UTC
Labels: Bug
