### ISSUE TITLE
Player Input Logic Fails to Broadcast Off State

### ISSUE THREAD

**Issue by grafvonzan** [tsunamayo/Skywanderers#517] opened 2017-12-16 23:06 UTC
It does not appear that player input blocks, like the "Left/Right/Middle Mouse Button" blocks, send their off state to whatever logic they are connected to. 

For example, if I hook up a 'Left Mouse Button' block to a 'Dual Link Gate', activating the 'Left Mouse Button' block sends a 1 signal, but not the 0 signal, causing the 'Dual Link Gate' to forever store a 1.

**Comment by tsunamayo** [comment] 2017-12-17 00:09
Hi, yes it is by design. What kind of mechanism you want to achieve? Skywanderers logic is pulse based, not state based. (but I could send a 0 on mouse release). Thanks

**Comment by grafvonzan** [comment] 2017-12-17 02:09
Hi! Having loads of fun with your game- I'm glad I backed it!

I am trying to make a device that fires a laser rapidly when the left mouse button is held down (to make a rotating Gatling gun weapon). My first attempt was foiled by the off state not being broadcast. I was able to get it so that clicking the button once turned on the firing system, and clicking again turned it off, but that isn't quite what I wanted to do. Sending a 0 on mouse release would solve that problem.

**Comment by schlid** [comment] 2017-12-29 05:33
A way to resolve this would be to remove the "mouse 1 mouse 2 hotkey1 hotkey2" types of shortcut logic, and replacing them with a toggle, held, and pulse, shortcut logic, where you assign a key through GUI. 

Toggle would emit regular "1" states when activated by pressing the key, and then would stop emitting the "1" states when pressed again.

Held would emit regular "1" states whilst the key is pressed

and finally, the pulse would act like the current shortcut buttons, emitting a single "1" state on a key press.

**Comment by tsunamayo** [comment] 2020-03-18 05:12
Issue is fixed with the new system. Hotkey are sending their off state too. Thanks!

**Closed by tsunamayo** 2020-03-18 05:12 UTC
Labels: Question
