### ISSUE TITLE
Bug with Invisible plants

### ISSUE THREAD

**Issue by Balibalou** [tsunamayo/Skywanderers#453] opened 2017-11-18 22:10 UTC
I was building a greenhouse in space withe a lot of cockpit and after a lot of plants after finishing the glasse part I began placing plants, at some point I the blocks I put are invisible, they are here because I can't pass thru them.

I tried to start a new game a load the model, I have the same issue.

client 17ww45c

![image](https://user-images.githubusercontent.com/19994792/32985200-9bf70eb6-ccb5-11e7-863c-16bc392563f9.png)

**Comment by Balibalou** [comment] 2017-11-18 22:21
after deleting the plants, saving the game and importing the model in a new game, the model works and I can put plants.

I could redo the bug by adding plants another time, I read it can be the limit of polygon.

**Comment by CyaNox** [comment] 2017-11-19 07:30
Even though plants are not bricks this may be a duplicate of #312.

**Comment by tsunamayo** [comment] 2017-11-20 08:45
Yes I guess it is a duplicate of #312 ... Plants are bricks in the code ;-) Anyway this should be fixed one day, I might do a temp fix as unity allows 32bit indexes now. Cheers

**Closed by tsunamayo** 2017-11-20 08:45 UTC
