### ISSUE TITLE
User Interface Bug - Pause Menu

### ISSUE THREAD

**Issue by Slyrae** [tsunamayo/Skywanderers#194] opened 2017-10-25 18:07 UTC
**Isssue:** Multiple menus can overlay each other at the same time, namely options menus.

**How to reproduce:** Pause the game, go to options, then click any of the four items; Game, Graphics, Audio, Controls. Then press Esc to close everything at once. Pause the game again, then navigate back to Options. The last category you were previously in will now be displayed as well.

It also appears that until you relaunch the game, the UI will continuously overly atop itself each time you navigate back to Options.

_Discovered 2:05pm U.S. Eastern Standard Time on October 25, 2017_

**Comment by ike709** [comment] 2017-10-25 18:10
Dupe of #170

**Comment by tsunamayo** [comment] 2017-10-25 23:34
This issue have been fixed - it will be up in the next patch. Thanks!

**Closed by tsunamayo** 2017-10-25 23:34 UTC
Labels: bug
