### ISSUE TITLE
[Bug] Artifacts in drone menu

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1644] opened 2020-03-04 17:14 UTC
### Short Description of the issue:
Black squares pop up and flash in the drone menu, but only when you're moving. Weird as it sounds, it seems like the player moving makes these weird shapes flash about

### Steps to reproduce the issue:
Fly towards the drone, then interact with it while still moving

### Environment
- Skywanderers version: 20w09a
- Graphics Card: RX 580 8GB

### Additional information:

![Skywanderers Drone Artifacts](https://user-images.githubusercontent.com/27857711/75904690-9428ba80-5e3b-11ea-9b0b-1f15645da1d9.gif)
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/4288664/output_log.zip)

**Comment by tsunamayo** [comment] 2020-03-05 06:57
hoho thanks for this one, I saw it indeed but never noticed that it was linked to the player moving... I keep you posted!

**Comment by tsunamayo** [comment] 2020-03-10 23:36
Okay actually I dont manage to reproduce this, are you seeing this consistently? Thanks

**Comment by tsunamayo** [comment] 2020-03-10 23:47
I made some change that could impact this, if you are still seeing this after the next update ping me! Thanks a lot!

**Comment by ProPeach** [comment] 2020-03-10 23:50
I am, it happens every time I open up the drone menu.
Interestingly I just booted up the game on my laptop (GTX 1050M) to double check this before answering and it seems that the explosion effect also causes artefacts to appear on the drone menu. I haven't reset this world save after the galaxy system resize so all my ships reset to the centre of the sun which is why the sky is black.
![image](https://user-images.githubusercontent.com/27857711/76368886-8f777100-6329-11ea-832c-75f3b1ab2e9c.png)

**Comment by tsunamayo** [comment] 2020-03-11 00:04
Okay, I guess there might be a bunch of problem linked to that.
Also the explosion is a bit special, I think I will have to change it because it cause all sort of problems with transparency.
Anyway if you could tell me if you reproduce in a normal place (start a new character) with the nvidia!
New patch is up soon. Thanks!

**Comment by ProPeach** [comment] 2020-03-11 00:55
Did some more testing on the Nvidea card, I can't seem to reproduce it this way. It could be an AMD only issue, but I'll keep playing for longer on the GTX to make sure it's not just a rarer occurrence

**Comment by tsunamayo** [comment] 2020-03-17 06:48
Okay if you tell me if you reproduce on an AMD card with the latest 20w12a! Thanks

**Comment by ProPeach** [comment] 2020-03-17 19:49
Thanks for the patch! I can still reproduce these errors, but they're much smaller and less frequent.
![image](https://user-images.githubusercontent.com/27857711/76895524-15466f80-6888-11ea-9bc2-2c560e357632.png)
I've also discovered that they only seem to appear when a menu is drawn over the line in yellow. It seems to be a circle that follows the ringworlds curve, while intercepting the flashing red and blue lights. For whatever reason the artifacts only generate on this line. It's much easier to see in motion, and if you observe it from different angles. Hope this helps!

**Comment by ProPeach** [comment] 2020-03-17 19:54
Update - Looks like you can also see them when you look at the asteroid rings on the gas giant too, but again only along that yellow line. I thought a video would be more helpful here, again on the AMD card.
[Skywanderers Artifacts.zip](https://github.com/tsunamayo/Skywanderers/files/4345540/Skywanderers.Artifacts.zip)

**Comment by tsunamayo** [comment] 2020-03-19 05:07
Great investigation! I was able to see the artifact, it is now clear it must be related to the torus fog. I keep you posted!

**Comment by tsunamayo** [comment] 2020-03-19 11:04
Okay great, this will be fixed in next update! Thanks a lot for tracking that one. Cheers

**Closed by tsunamayo** 2020-03-19 11:04 UTC
Labels: Bug
