### ISSUE TITLE
Default acceleration key mapping issue (17w45b)

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#438] opened 2017-11-13 02:23 UTC
Build: pre-alpha 17w45b

This started when this build was deployed. The default [ and ] keys still show as mapped, but when you try to fly in standard mode, ship doesn't move. Other flight modes worked. I was able to get around this by manually setting the alternate key mapping for these to the same as the default.

**Comment by CyaNox** [comment] 2017-11-13 02:27
Duplicate of #431 and fixed in 17w45c (experimental branch).

**Closed by CyaNox** 2017-11-13 02:27 UTC
Labels: Duplicate
