### ISSUE TITLE
[Bug] Collision detection not working for child entities [20w10a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1647] opened 2020-03-06 19:45 UTC
### Short Description of the issue:
The game does not seem to detect at least some collisions.

### Steps to reproduce the issue:
Place a rotator and add blocks to it so that when it turns they will pass through other blocks on the parent entity, then switch the rotator. The attached blocks on the child entity will sweep through the ones on the parent entity.

I discovered this when working on turrets; I still need to check the hinge and slider. Will update this when I get a chance to check those.

### Environment
- Skywanderers version: 20w10a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200306134009_1](https://user-images.githubusercontent.com/33041786/76116991-8f394780-5fb0-11ea-906d-5604019c508d.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4300141/output_log.txt)

**Comment by tsunamayo** [comment] 2020-03-10 07:31
Okay I cant reproduce the issue, if you could send me your mini bp. Maybe it was already fixed...
Thanks!

**Comment by Dwarf-LordPangolin** [comment] 2020-03-10 19:38
Sure! Here's one with the issue.

[Clipping Test Blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/4314408/Clipping.Test.Blueprint.zip)

**Comment by tsunamayo** [comment] 2020-03-10 22:56
Okay thanks I can now reproduce! I keep you posted.

**Comment by tsunamayo** [comment] 2020-03-10 23:22
Okay I increase a bit my normal offset and it was a quick fix. It should not impact other case adversely, but if it breaks one of your mechanism please tell me! Will be in next patch. Cheers!

**Closed by tsunamayo** 2020-03-10 23:22 UTC
Labels: Bug

**Comment by Dwarf-LordPangolin** [comment] 2020-03-21 02:22
Awesome! All the mechanisms like ramps and landing gear seem to still work fine. :3
