### ISSUE TITLE
[Bug] Ringworld spawns rocks when you approach it

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1537] opened 2020-01-08 23:46 UTC
### Short Description of the issue:
When you fly close to the ringworld, clusters of rocks spawn in an area beneath you. They have no collision and despawn when you move away from them. Video attached below. The rocks only appear on the sand, water and grass, never the rocks leading me to believe it's an LOD error.
Ringworld looks amazing though!
...

### Steps to reproduce the issue:
Fly close to the ring and watch for rocks
...

### Environment
- Skywanderers version: 20w02a
- Graphics Card: GTX 1050M

### Additional information:

[Skywanderers Rock Spawn Bug.zip](https://github.com/tsunamayo/Skywanderers/files/4037893/Skywanderers.Rock.Spawn.Bug.zip)

**Comment by tsunamayo** [comment] 2020-01-09 00:22
Hi, could you give me your log file?
Also there seems to be many issues with the torus on the lighting side... If you could send me some various screenshot of what you see I also need to investigate that.
Are you up-to-date on your GFX drivers? Thanks

**Comment by ProPeach** [comment] 2020-01-09 00:29
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4037974/output_log.txt)
Here we are. I also realized I was wrong about by GPU - I have an RX 580, I got mixed up as I only recently got it. According to Radeon software I am up to date on my drivers, although Womble-TC also has the same issue on an AMD card

**Comment by ProPeach** [comment] 2020-01-09 00:33
Here are some screenshots. The glowing line seems an out of place shadow, and there is no light from the sun in the case
![image](https://user-images.githubusercontent.com/27857711/72027582-84e02300-3277-11ea-965f-9916a37674f8.png)
![image](https://user-images.githubusercontent.com/27857711/72027589-8ad60400-3277-11ea-9a87-4df2f17042ae.png)
![image](https://user-images.githubusercontent.com/27857711/72027600-94f80280-3277-11ea-8ad4-d445e7d25a6e.png)


![image](https://user-images.githubusercontent.com/27857711/72027589-8ad60400-3277-11ea-9a87-4df2f17042ae.png)
![image](https://user-images.githubusercontent.com/27857711/72027610-99242000-3277-11ea-9cd7-ec8b57e31534.png)

**Comment by tsunamayo** [comment] 2020-01-09 01:30
Do you have trouble to collide with the groud? At normal speed that is.

**Comment by Garrett-C** [comment] 2020-01-09 01:31
occasionally yeah. It's fine most of the time.

**Comment by ProPeach** [comment] 2020-01-09 01:31
I have no issue at low speeds, although it feels a bit too slippery even on shallow slopes

**Comment by Starwhip** [comment] 2020-01-09 01:49
Also experiencing this bug, AMD graphics card, which seems to be the cause

**Comment by ExodistSKY1** [comment] 2020-01-09 01:50
As for the colliding with ground, when walking into the deeper parts of the water you will end up walking through the ground.

It does seem that the character will slip down a shallow slope to confirm what ProPeach had stated above.

**Comment by Aiwii** [comment] 2020-01-09 01:53
I also have this Issue and an AMD card [AMD Radeon(TM) RX Vega 11 Graphics] my character doesn't collide with the ground though I kinda just move through it.

**Comment by tsunamayo** [comment] 2020-01-09 06:39
Okay it is gonna be a nightmare again to debug, I dont have the hardware, and there is nothing in the error.log. @Aiwii @Starwhip could you also please give me your log file? Thanks

**Comment by AfterRebelion** [comment] 2020-01-09 10:46
AMD RX 580 user here, driver version 19.12.3 (The latest one), and also got this bug with giant rocks on the habitat.
![imagen](https://user-images.githubusercontent.com/559819/72060993-4a0cd800-32d5-11ea-9acd-431a9ea6ae1c.png)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4039957/output_log.txt)

Looking at pictures of other people in the habitat, it seems like the decorative rocks on the ground don't scale properly, and blew out of proportions.

**Comment by Aiwii** [comment] 2020-01-09 18:00
@tsunamayo 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4041774/output_log.txt)

Also noticed this with the grass when I just walk into the rocks
![Skywanderers 2020-01-09 10_56_22 AM](https://user-images.githubusercontent.com/53021785/72092157-f8614f00-32ce-11ea-9253-c495fc2efee7.png)
Its generates bunched up in a line which may also be an issue. My rocks generate weirdly like everyone else's though 
![Skywanderers 2020-01-09 10_56_48 AM](https://user-images.githubusercontent.com/53021785/72092217-1dee5880-32cf-11ea-9bfc-63a2444155e9.png)
Standing on Mountains is fine
![Skywanderers 2020-01-09 10_57_30 AM](https://user-images.githubusercontent.com/53021785/72092252-2ba3de00-32cf-11ea-899f-5f5dcb99778e.png)

**Comment by tsunamayo** [comment] 2020-01-10 00:30
Okay thanks for your contribution all. I will push a new update tonight, you will tell me if that fixes the issue. It will likely take a few build to get it fixed, in the worst case I will have to buy an AMD card...
Thanks!

**Comment by ProPeach** [comment] 2020-01-10 10:03
I have an Nvidia laptop as was as an AMD PC, I'd be more than happy to run some tests if you need a comparison

**Comment by AfterRebelion** [comment] 2020-01-10 12:20
Sadly, 20w02b doesn't fix this:
![imagen](https://user-images.githubusercontent.com/559819/72152689-03d67800-33ac-11ea-89f2-db4bc2f9322e.png)

**Comment by Aiwii** [comment] 2020-01-10 20:26
![Skywanderers 2020-01-10 1_24_59 PM](https://user-images.githubusercontent.com/53021785/72184032-adb60480-33ac-11ea-9100-c6584cfad27b.png)
![Skywanderers 2020-01-10 1_24_42 PM](https://user-images.githubusercontent.com/53021785/72184034-aee73180-33ac-11ea-839c-cb8616c38334.png)
Generation problems still persist sadly. I really like the addition of blast doors though

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4047781/output_log.txt)

**Comment by AfterRebelion** [comment] 2020-01-13 13:25
As a workaround, you can disable stone rendering on the debug menu (F3)
![imagen](https://user-images.githubusercontent.com/559819/72259327-75166500-3610-11ea-9cca-3818dc967cf6.png)

Thanks to Aiwi on Discord for finding that out.

**Comment by AfterRebelion** [comment] 2020-01-24 17:17
Seems fixed in 20w04a! :D
![imagen](https://user-images.githubusercontent.com/559819/73088993-a7a84380-3ed5-11ea-9aea-a39c564a87ba.png)

Had to say, the habitat looks gorgeous with the grass and other assets rendering correctly.

**Comment by ProPeach** [comment] 2020-01-24 18:05
![image](https://user-images.githubusercontent.com/27857711/73092164-f94fce80-3ed3-11ea-9a60-85cf18e86075.png)
RX 580 user here, looks like you've done it! We can finally appreciate it in all its glory

**Comment by tsunamayo** [comment] 2020-01-24 23:46
haha super I have made a change indeed, I forgot to tell you to reactivate the grass / stone to check but you did it anyway! So glad we fixed that one! Cheers

**Closed by tsunamayo** 2020-01-24 23:46 UTC
Labels: Bug
