### ISSUE TITLE
Painting mirrored blocks creates blocks

### ISSUE THREAD

**Issue by JLAMontoya** [tsunamayo/Skywanderers#331] opened 2017-11-01 02:40 UTC
I have an antenna on top of a ship, and nothing on the bottom of the ship. I have the mirror blocks placed, and when I paint the antenna, it creates another antenna on the bottom of the ship (it also paints it), as if I had built it.

Not a game-breaking bug.

**Comment by CyaNox** [comment] 2017-11-01 06:09
Duplicate of #292.

**Closed by CyaNox** 2017-11-01 06:09 UTC
Labels: Bug, Duplicate, Reproduced
