### ISSUE TITLE
Problems with hoses

### ISSUE THREAD

**Issue by Centauri2442** [tsunamayo/Skywanderers#279] opened 2017-10-29 03:10 UTC
Connecting hoses in a straight line from each other causes them to glitch out.

![20171028220757_1](https://user-images.githubusercontent.com/28989460/32140372-dd2c2bd0-bc2c-11e7-820a-9e0b70eb846a.jpg)

![20171028221037_1](https://user-images.githubusercontent.com/28989460/32140374-de8663d8-bc2c-11e7-9f38-3c517a6b8bd9.jpg)

**Comment by CyaNox** [comment] 2017-10-29 03:32
Related to: #239

**Comment by AfterRebelion** [comment] 2019-06-06 14:07
As already stated, duplicate of https://github.com/tsunamayo/Skywanderers/issues/239

**Closed** 2019-06-06 23:10 UTC
Labels: Bug
