### ISSUE TITLE
Mirrored bricks do not render until the next brick is placed

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1624] opened 2020-02-27 20:10 UTC
### Short Description of the issue:
When placing a brick with mirror enabled, you can see that while bricks are placed correctly on both sides of the mirror plane one of them is invisible until you place the next brick (video included)

As a side note, the new brick glass is awesome, but would it be possible for it to start at 0.25m^3 size rather than the current 0.5m^3? That would be truly amazing!
...

### Steps to reproduce the issue:
Sadly I haven't been able to pin down what causes this specifically. The best way I've found of reproducing this is to load up the game, place a mirror plane and then start placing bricks. When I alt tabbed back to the game after reporting this issue, it had fixed itself.
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: TX580 8GB

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4263866/output_log.txt)
[Skywanderers Mirror Bug.zip](https://github.com/tsunamayo/Skywanderers/files/4263870/Skywanderers.Mirror.Bug.zip)

**Comment by Aiwii** [comment] 2020-02-28 05:13
I think this is similar to issue #1566 and the cause it placing near the mirror plane

**Comment by tsunamayo** [comment] 2020-03-26 06:49
Okay this issue is now fixed! Thanks

**Closed by tsunamayo** 2020-03-26 06:49 UTC
Labels: Bug
