### ISSUE TITLE
Impossible to use the same keybind for 'Crouch' and 'Drive -' command

### ISSUE THREAD

**Issue by HadesDeadlyTom** [tsunamayo/Skywanderers#211] opened 2017-10-26 09:24 UTC
It's either you can assign the same key and, the drive- command doesn't work, or you lose your character movement like #192.

**Comment by tsunamayo** [comment] 2017-10-30 07:38
Hi! I think that most probably you try to assign to a bugged key (did you try Capslock?) and the game went unresponsive. Could you please send me your output_log? Thanks!

**Comment by HadesDeadlyTom** [comment] 2017-10-30 11:09
Hi Tsuna, I'va tried with a lot of keys but i can't get it to work.
I've made a little video if that can help you : 
https://www.youtube.com/watch?v=Aj-g_3gPh7Q
and here is the : [output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1426832/output_log.txt)

**Comment by tsunamayo** [comment] 2017-10-30 11:11
Okay what is the last key that you tried? Is it just B? Thanks!

**Comment by HadesDeadlyTom** [comment] 2017-10-30 11:21
Right now i have Capslock for both.
As when i've made the output_log.

**Comment by tsunamayo** [comment] 2017-10-30 23:29
Okay I got it thanks for the video, it is not a bug, you switch Drive with Switch Drive key. Only once in Hyper Drive, you can use Drive + and Drive -. This is all gonna change anyway for the flight control refactoring. Then Caps Lock key is not working. Thanks

**Comment by tsunamayo** [comment] 2017-10-30 23:34
Correction Caps Lock key is working fine, so I guess it was just this bug (maybe you tried another key at one point) Cheers!

**Closed by tsunamayo** 2017-10-30 23:34 UTC
Labels: Bug
