### ISSUE TITLE
lighting not showing correctly.

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Skywanderers#684] opened 2018-04-01 20:30 UTC
before placing the light....
![20180401211753_1](https://user-images.githubusercontent.com/7197427/38177137-8922033e-35f3-11e8-81b0-1d77865f151e.jpg)

after placing the light....

![20180401211757_1](https://user-images.githubusercontent.com/7197427/38177144-b41059b0-35f3-11e8-9462-4e5e7ce3e78e.jpg)

the light shines, is on, but doesn't display correctly. reproducible on the attached blueprint
[The Odyssey.zip](https://github.com/tsunamayo/Skywanderers/files/1866681/The.Odyssey.zip)

**Comment by Vicomt** [comment] 2018-04-01 20:33
reloading the save fixes the display of the light once it's been placed

**Comment by tsunamayo** [comment] 2018-04-11 00:05
I am not reproducing, did you manage to reproduce on the latest experimental? Thanks

**Comment by BonnyORG** [comment] 2018-04-18 17:25
@tsunamayo When placing the light blocks on child entities it mostly looks like shown in the picture

**Comment by tsunamayo** [comment] 2018-06-04 07:51
Hi, I fixed an issue that could have explain this one, and I cant reproduce your issue. Dont hesitate to re-open if it is not fixed in next update! Thanks

**Closed by tsunamayo** 2018-06-04 07:51 UTC
Labels: Bug, Cannot Reproduce
