### ISSUE TITLE
Bug - Game doesnt seem to be saving anything

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#650] opened 2018-03-26 07:50 UTC
Hi, so I was playing for about 9 hours straight today, just as I usually would, on the new experimental version. 
I was saving and making sure that everything was saved before closing the game, however when I restarted it, all 9 hours of work were gone. I checked the blueprints folder and found that the last time the swbp file of the ship I was working on was edited, was in fact when I first exported the model to the new BP systems about 8 hours before hand.
I checked the player entities folder and found a swbp file that appears to be exactly what I was working on, the file size was right, and the time it was last edited was perfect to the minute.
So after I went back in game, the world was the same except all the ships I had spawned in and had worked on were gone.
On top of this being a bit of a bug with the game not saving work except for ships being exported to a new blueprint file, I was hoping there might be a way I can get back my ship I was working on through the Player Entities swbp file of what I believe to be my ship.

[SWBP Files.zip](https://github.com/tsunamayo/Skywanderers/files/1846804/SWBP.Files.zip)

I have attached the player entities and blueprint file of the ship in the above zip file

Also as has already been reported, the game isn't saving things in the settings file. The volume resets every restart, and all controls except for the alternate controls get reset too.

Hoping something can be done :)

**Comment by tsunamayo** [comment] 2018-03-26 08:25
Sorry to hear that! Could you please give me all your save folder, I also need the Instances folder. How many ship where not restored? Can you send them all? Thanks

**Comment by Sullos** [comment] 2018-03-26 08:35
[All save data things.zip](https://github.com/tsunamayo/Skywanderers/files/1846990/All.save.data.things.zip)

I have attached my entire save_data folder
However it includes all my blueprints.
I had spawned in, and had left the following ships in game:
[New] [WIP] Ancient Bomber
zpm module mk2
Sullosian Viper V3.5

All torus structures were left there and still remained. However the above structures were in the world and upon leaving the game and restarting, they were all gone, and the blueprint file hadnt been updated with the newer version which I had been working on.
I was actively working on the [New] [WIP] Ancient Bomber swbp 
Thanks :)

**Comment by tsunamayo** [comment] 2018-03-26 08:40
Thanks I will have a look at it.
I saw you where using some unholy building technique on your big bomber, I will have to do something to prevent that... It might not be related to the new save folder, as this ship was clearly pushing the envelop too much.
Cheers

**Comment by Sullos** [comment] 2018-03-26 08:51
Ah yes, I presume you mean the rotator wall pieces. ;D
That was intended as a way for me to figure out wall placement, and I am indeed in the process of the building them from scratch instead of leaving them on the rotators.
It is certainly a cheat way of doing things, but I do definitely plan to continue building them all manually and replacing the ones cheat placed in.
It was affecting my games frame rate, and overall is just a bit 'unholy' as you put it.

However in any case I do believe that it shouldn't have been affecting anything, as there were many more wall pieces placed in an earlier version of the build before I had started rebuilding them in their desired position. It is only since the update that I have experience such issues.
:)

**Comment by Name11ess** [comment] 2018-03-26 10:03
> I saw you where using some unholy building technique on your big bomber, I will have to do something to prevent that...

How do you plan to prevent doing something like that? I'm wondering because some parts of my actual project needs a few child entities to be combined to allow a particular shape to be done. Of course it's not as violent as Sullos, but a drastic limitation could make my project inconstructible.

**Comment by Tomatart** [comment] 2018-03-26 20:24
This happened to me with the same ship (we are working on it together) I loaded the BP and the freeform blocks had random textures, so i exported the BP with a new name and respawned it. the newly spawned ship was reverted to a save from days ago.

**Comment by tsunamayo** [comment] 2018-03-29 06:15
It is weird, I dont see how this could happens. You have the original blueprint so I can do the export and see for myself? thanks

**Comment by Tomatart** [comment] 2018-03-29 06:19
I do not, however the same thing happened with this ship
[Ship BP.zip](https://github.com/tsunamayo/Skywanderers/files/1858789/Ship.BP.zip)
After exporting and respawning to fix the texture issue, the build had all the lights broken and recent progress was lost

**Comment by tsunamayo** [comment] 2018-03-29 06:22
@Tomatart thanks I am having a look at it.
@Sullos could you please assign the control the way you do usually, and send me the SETTINGS.ini file? I want to see what is wrong with it as I dont reproduce. Thanks

**Comment by tsunamayo** [comment] 2018-03-29 06:29
![unity 2018-03-29 15-28-12-36](https://user-images.githubusercontent.com/6604318/38073426-f0181c26-3365-11e8-9fdc-9caf05781de9.png)
Both ships look similar, where do I need to look for differences?

**Comment by Tomatart** [comment] 2018-03-29 06:35
Thats odd... there are details missing on the top of the ship on both that
were there when i first exported.
The file i sent you was the .swbp from the PlayerEntities folder used prior
to the update, however it was not backed up prior to exporting,

Is it possible that after exporting both the original Blueprint and the
newly exported Blueprint were reverted?

**Comment by Tomatart** [comment] 2018-03-29 06:36
Also when i did it all the lights on the ship were "on" but not emitting
light, but you don't seem to be having that problem

**Comment by Sullos** [comment] 2018-03-29 23:16
Here is my settings.ini file.
Oddly the alternative controls dont reset, but the primary ones, seem to reset to default If I change them. Usually after a reboot.
[Settings File.zip](https://github.com/tsunamayo/Skywanderers/files/1862213/Settings.File.zip)

Further more, I have discovered that the saving also seems to affect ships of the same type, but not of the same version.
For example, my world appears to be saving for the most part, every time I load the game now, I can see an old version of my bomber which I never deleted. It was version 4.
However, eveytime I load into the world I spawn in the current version which is currently being worked on. Which these days is about version 23.
So the versions are very different, but the game isn't allowing both ships to be in the world at the same time. Pressing f1 doesn't seem to save anything if I have two of the same ship, despite the fact they are saved as different versions.

Another discovery I have made is that if the world has two different versions of the same ship in the world (as described above) then saving of the newer version doesn't happen at all.
This means that to save any progress on the new version of the ship we are working on, I have to re export it every time I want to 'save', to prevent losing progress.

Hope this helps track down the saving issues we have been having. :)
Thanks

**Comment by tsunamayo** [comment] 2018-03-30 00:54
Hi, as I have your save state, could you please give me a clear test case? Like what ship are you loading in that doesnt not get saved (if you have several please pick up the smallest one)? Thanks

**Comment by Sullos** [comment] 2018-03-30 09:31
So by having the Ancient Bomber, that Tomatart and I have been building if an older version is in the world and the game is saved, and a newer version is also spawned into the world, it will not save the newer version.
So the blueprint file names should be 
[New] [WIP] Ancient Bomber v1, for example, and if I spawn in [New] [WIP] Ancient Bomber v8 or so, then the changes made onto the more recently spawned in ship don't get saved.
I don't believe it is a matter of the ship being the problem, however, when I get the chance I will test it with other ships of various types.

**Comment by tsunamayo** [comment] 2018-03-30 11:47
Yes if you could test with other ship that would be great! Could you please send me [New] [WIP] Ancient Bomber v1 and [New] [WIP] Ancient Bomber v8 so I can reproduce? Thanks

**Comment by tsunamayo** [comment] 2018-04-01 01:42
Okay I think the issue will be fixed in next patch, please tell me if it is not the case. I think to get your old blueprint you need to have only one instance currently loaded, so delete first your old ship from the world - then load your blueprint, and re-export it to fix the issue. Thanks

**Closed by tsunamayo** 2018-04-01 01:42 UTC
Labels: Bug
