### ISSUE TITLE
Lighting can get stuck in on state when placing/breaking blocks near it.

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#458] opened 2017-11-20 09:25 UTC
I'm not sure how to describe this exactly but in some cases when breaking blocks the light may get "stuck" on.

Even after removing the actual source of the lamp it still seems to emit light.

The video below shows how I managed to reproduce it (fairly reliably): https://youtu.be/e76alTwzZq0

Blueprint: 
[Bug Lighting Stuck.zip](https://github.com/tsunamayo/Skywanderers/files/1487055/Bug.Lighting.Stuck.zip)

**Comment by tsunamayo** [comment] 2017-11-23 05:32
Okay as I planned to move lighting computation to compute shader I am not gonna fix this one until the new system is up. Thanks

**Comment by tsunamayo** [comment] 2017-11-30 02:55
Hi, after the few fixes I did on the light computation I am not able to reproduce this bug. Please re-open if it is not fixed on your side (on experimental). Thanks!

**Closed by tsunamayo** 2017-11-30 02:55 UTC
Labels: Bug
