### ISSUE TITLE
[Bug] Torus not rendering properly

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Skywanderers#1668] opened 2020-03-27 06:14 UTC
### Short Description of the issue:
Torus isn't rendering properly
![Skywanderers 2020-03-27 12_09_31 AM](https://user-images.githubusercontent.com/53021785/77727223-6c062480-6fbf-11ea-8a07-1ce855144fd5.png)
![Skywanderers 2020-03-27 12_09_40 AM](https://user-images.githubusercontent.com/53021785/77727225-6d375180-6fbf-11ea-8db8-8b68a4e8b988.png)

...

### Steps to reproduce the issue:
- Go to Torus
- Issue

### Environment
- Skywanderers version: 20w13a
- Graphics Card: AMD Radeon(TM) RX Vega 11 Graphics

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4391828/output_log.txt)

**Comment by AfterRebelion** [comment] 2020-03-27 06:50
Can confirm this issue with AMD RX 580.

**Comment by tsunamayo** [comment] 2020-03-27 10:17
Okay thats seems another AMD related issue I guess. 
I made some change to the terrain rendering to make it faster CPU and GPU side.
I will push an updated soon - I keep you posted
Thanks!

**Comment by BFett2000** [comment] 2020-03-27 20:10
GeForce GTX 1060 also having same issue.

**Comment by tsunamayo** [comment] 2020-03-28 00:32
@Aiwii @AfterRebelion @BFett2000 did you faced this issue after going back to the start screen and then getting back in the game?

**Comment by ProPeach** [comment] 2020-03-28 02:02
I encountered this issue the first time I loaded up my world after updating, I also use an RX 580

**Comment by ultrak2k** [comment] 2020-03-28 02:27
Ive had this issue also - been using AMD Raedon 7500 HD series

**Comment by BFett2000** [comment] 2020-03-28 04:22
@tsunamayo Yes the issue is still present after quitting to menu and loading back in.

**Comment by BFett2000** [comment] 2020-03-28 04:28
![20200327211342_1](https://user-images.githubusercontent.com/62455810/77814801-b647de00-7071-11ea-9ebe-7d87414678b7.jpg)
![20200327211436_1](https://user-images.githubusercontent.com/62455810/77814814-c495fa00-7071-11ea-85c6-f97fc4cb6838.jpg)
Here's a couple additional screenshots from my machine.

**Comment by tsunamayo** [comment] 2020-03-28 04:35
@BFett2000 actually what I want to know is if have the issue on your first load. 
I wanted to make sure it was an issue related to reloading the game after going back to title screen, which was a different bug (that I just fixed).
I had reproduced the issue only on the second load (after going back to the screen).

**Comment by BFett2000** [comment] 2020-03-28 04:36
Oh, This is on the first load, and all subsequent loads as well.

**Comment by tsunamayo** [comment] 2020-03-28 06:08
okay gotcha @BFett2000 , I tested with my GTX 1060 and had no issue. Could you send me your output.log so I can check if there is something? It might be a different issue.

**Comment by BFett2000** [comment] 2020-03-28 06:16
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4396714/output_log.txt)
@tsunamayo  Here you go!  Hope it helps.

**Comment by Aiwii** [comment] 2020-03-29 00:09
Yea my first load into the game was like that, ill see what happens when I reload

**Comment by tsunamayo** [comment] 2020-03-29 03:08
Okay I pushed a new build, if you could tell me if that fixed the issue or not! Thanks

**Comment by BFett2000** [comment] 2020-03-29 03:35
It looks great now! Thank you!

**Comment by tsunamayo** [comment] 2020-03-29 04:19
Okay great, I will wait for an AMD return before closing this!

**Comment by AfterRebelion** [comment] 2020-03-29 08:34
AMD RX 580, Torus renders correctly in 20w13b :D
![imagen](https://user-images.githubusercontent.com/559819/77844673-c3b3b400-71a8-11ea-96e9-989025d7ed3a.png)

**Comment by tsunamayo** [comment] 2020-03-29 08:36
Fantastique! Case closed.

**Closed by tsunamayo** 2020-03-29 08:36 UTC
Labels: Bug
