### ISSUE TITLE
[EXPERIMENTAL] Multitool Color Bulb 

### ISSUE THREAD

**Issue by BonnyORG** [tsunamayo/Skywanderers#757] opened 2018-04-19 19:05 UTC
When deleting a selected color, the multitool keeps showing it.
![20180419210230_1](https://user-images.githubusercontent.com/38502325/39012684-672bd158-4415-11e8-95df-210cbf29eebb.jpg)
![20180419210236_1](https://user-images.githubusercontent.com/38502325/39012685-674a84e0-4415-11e8-8efe-cebb8e55df55.jpg)
![20180419210239_1](https://user-images.githubusercontent.com/38502325/39012686-6762bf60-4415-11e8-863e-a0cc8a382e95.jpg)

Version: 18w15b

**Comment by BonnyORG** [comment] 2018-04-21 09:11
I can reproduce this every time with any color bulb

**Comment by JRL101** [comment] 2018-04-22 02:46
I've been trying to force this to reproduce, did you have anything else on the other toolbars?

**EDIT.. oh.. err i cause something different. From changing tool bars after removing stuff from bar one .**
![20180422104502_1](https://user-images.githubusercontent.com/33255536/39090781-65074c20-461a-11e8-9c6c-bef780037fe7.jpg)

**Comment by JRL101** [comment] 2018-04-22 02:50
**# Okay got it to replicate! :)**
![20180422104945_1](https://user-images.githubusercontent.com/33255536/39090803-f478cc94-461a-11e8-8ef0-c081f4d3e796.jpg)


Holding SHIFT and scrolling thorough the tool bars on a slot with something in it returns it back to normal. (SOMETIMES)
So from how i replicated it:
Place Paint in slot

**Comment by JRL101** [comment] 2018-04-22 02:55
Good find BunnyORG.

**Comment by BonnyORG** [comment] 2018-04-23 07:57
Shifting to another tab is not necessary (at least not for me)
You just need to have the color selected, then go into your inventory to remove it, close it and voila

**Comment by tsunamayo** [comment] 2018-04-23 23:34
Thanks for the finding, the issue is now fixed! Cheers and thanks for being so active! ;-)

**Closed by tsunamayo** 2018-04-23 23:34 UTC
Labels: Bug
