### ISSUE TITLE
Hinge speeds seem much slower (17w45a2)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#397] opened 2017-11-07 13:54 UTC
Not sure if this is a bug or an intentional tweak, but hinges are moving much slower in this build than they were previously. It feels like they are moving at less than half of what their speed was before, even when nothing is built on them.

**Comment by CyaNox** [comment] 2017-11-07 15:21
Possibly a duplicate of #387. Can you confirm if it is that bug?

**Comment by Segdis** [comment] 2017-11-07 17:02
I don’t think it is, because my observations are based on constructions that I have not edited since the new build went live. I simply loaded the save in the newest build, and they are moving several times slower than they did in the previous version. This is also true for newly placed hinges that I have yet to build on. It seems like the maximum possible speed of hinges has been lowered, which is why I am not sure if it is a bug or an intentional change.

**Comment by tsunamayo** [comment] 2017-11-07 23:31
Hi, it was an intentional tweak, I will come with a better solution to control the speed of hinge. Thanks

**Closed by tsunamayo** 2017-11-07 23:31 UTC
