### ISSUE TITLE
[Experimental] Key rebindings reset on a game restart

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#381] opened 2017-11-05 23:54 UTC
I recently reset my keys back to the standard wasd movement, since they apparently don't default that way anymore, and after loading the game up today they reset back to the default keys.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1444582/output_log.txt)

**Comment by CyaNox** [comment] 2017-11-05 23:58
Duplicate of #364.

**Comment by tsunamayo** [comment] 2017-11-05 23:58
Hi! Okay so there a new assignment that need to be done from inside the game control binding. You did that already, and on next relaunch assignment was gone?

**Closed** 2017-11-05 23:58 UTC
Labels: Duplicate
