### ISSUE TITLE
[Bug] Block glitch, [Crash] Crash report, [Mini-suggestion] Warp tube

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#768] opened 2018-04-27 09:29 UTC
Since I don't want to spam more suggestions here, I may as well wrap two extra glitches into it. The glitch in question happens randomly when building. It is like the building is frozen. You can move, but you can't place a block. You can interact, but not go into a system (like you can hold select on a joystick, but it doesn't "connect.") Thankfully you can save, but the only way to fix it is quitting and restarting the game. I believe others have seen this as well, but as far as I know no one has got a video on it. Ill add my log, but it was hours ago when this occurred. This glitch has been in the game for a long time now so it may have been reported awhile back. Looking though 309 issues is not something to do at 2:30 AM. Ill make an effort to film it and post a more updated log. For now, awareness of this glitch is good enough.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1954542/output_log.txt)

I also randomly crashed earlier today for unknown reasons. Restarted the game and it did the whole "crashed game" message.  Not sure what caused it, but I may as well add it. Call it a double report
[error.log](https://github.com/tsunamayo/Skywanderers/files/1954515/error.log)

This just popped into my head and I don't mean to spam suggestions on the github. You know how you can color the core and it changes the color of the UI? A little idea is when you color the warp drive, it changes the color of the warp tube. Paint it pink and it will be pink. Green is green and so on. Dark blue is nice, but it would be a fun little addition :D

Call this a triple post. Two bugs for the price of one mini-suggestion. Have a good [insert general time of day here]

**Comment by Napther** [comment] 2018-04-27 21:30
Its better to seperate into 3 bug reports that can be closed individually.

**Comment by BonnyORG** [comment] 2018-04-30 20:16
I can confirm the first mentioned bug which seems to be some kind of soft lock. It occurs if you use the normal weapons to often while destroying some blocks. (I in particular was shooting on another ship when it first occurred, another time i was just shooting in the empty space but like 20 times in a short amount time)
It is always reproducible if you try to repair broken logic gate blocks.

**Comment by tsunamayo** [comment] 2018-05-02 08:06
Thanks, dont hesitate to book 3 different case as otherwise it is hard for me to track and ask info.
There is no error in the log you sent me, are you sure it is the right one? It gets overridden when starting a new game. Also for the crash can you send the output_log.txt file as this is the only useful one (sorry yeah it is confusing but its how Unity works).
I will close this as for now I only have two random issue with no step to reproduce and no log to investigate, but as soon as you get a log or a test case dont hesitate to book a new case! 
Cheers

**Closed by tsunamayo** 2018-05-02 08:06 UTC
Labels: Bug
