### ISSUE TITLE
[SUGGESTION]  Light indicator color change

### ISSUE THREAD

**Issue by ttmm3** [tsunamayo/Skywanderers#82] opened 2017-07-11 19:57 UTC
It would be great to have a version of the sloped light indicator that toggled between two different colors (EX: Red to Green and back) Based on the input, 0=Red 1=Green for example

**Comment by tsunamayo** [comment] 2017-09-26 23:23
Okay I see the need, maybe once multi colored brick are implemented it could be feasible.

**Comment by AfterRebelion** [comment] 2019-06-06 12:13
Duplicate of https://github.com/tsunamayo/Skywanderers/issues/92

**Closed** 2019-06-06 23:00 UTC
Labels: Suggestion
