### ISSUE TITLE
[BUG] W,A,S,D, keys are not mapped correctly when starting game (Experimental)

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#375] opened 2017-11-05 11:31 UTC
When starting the game in experimental, the keys listed above are not mapped correctly, with no output from A and D, and W and S moving the player at strange angles. This happens every startup even though they are set correctly in the key-mapping. (You can fix it in game by re-applying the key-binds, but I still thought it may be a bit annoying).

**Comment by CyaNox** [comment] 2017-11-05 11:48
Duplicate of #364.

**Closed by CyaNox** 2017-11-05 11:48 UTC
Labels: Duplicate

**Comment by tsunamayo** [comment] 2017-11-05 23:00
Okay, sorry it was indeed a crappy default mapping but it is fixed now. Cheers
