### ISSUE TITLE
[EXPERIMENTAL]Painting Some Freeform Blocks Turns Them Into Full Blocks

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#536] opened 2018-01-22 21:44 UTC
![2018-01-22_li_moment](https://user-images.githubusercontent.com/26584892/35246068-067ab9b0-ff8b-11e7-9733-a893a29c4b0e.jpg)
At the spots circled, when I paint them, they turn into full blocks for some reason. I can temporarily fix them by going into freeform edit mode and saving them, but after a bit, they lose their color again.

**Comment by JRL101** [comment] 2018-02-03 00:01
Can confirm, happens when leaving the edge of the freeform block if it is within the large grid. BUT it spawns a block under or next to the block you're painting, NOT overlapping the block you are painting.

**Comment by tsunamayo** [comment] 2018-02-04 02:23
@Senakysam hi, as it seems something you managed to reproduce at this specific place could you please give me your blueprint so I can fix it? Thanks!

**Comment by JRL101** [comment] 2018-02-04 11:14
@tsunamayo UPDATE- seems to be fixed in **[EXPERIMENTAL] 18w05a** I'm not able to re-create it. Seems to be gone.

**Comment by Senakysam** [comment] 2018-02-04 19:21
I can confirm that it is still there. And it definitely overlaps the block I'm painting, so we're talking about different issues JRL.

Here's the blueprint: 
[Shuttle03_WIP38.zip](https://github.com/tsunamayo/Skywanderers/files/1693214/Shuttle03_WIP38.zip)

**Comment by tsunamayo** [comment] 2018-02-05 02:45
Hi Sen, thanks for sending the bp. I can see the degenerate blocks, and they disappear after a validate, but I cant make them appear again. Are you doing something specific - or just painting the region should reproduce 100% of the time? Thanks

**Comment by Senakysam** [comment] 2018-02-05 03:36
I'll record a video tonight.

**Comment by Senakysam** [comment] 2018-02-05 05:10
Here's the video and the output_log

https://www.youtube.com/watch?v=fzCbR0hJqKI

[output_log Senakysam Freeform Paint Bug.zip](https://github.com/tsunamayo/Skywanderers/files/1693863/output_log.Senakysam.Freeform.Paint.Bug.zip)

The shuttle is 90% freeform, so I'm not actually surprised I broke it.

**Comment by tsunamayo** [comment] 2018-02-05 06:40
Oh fantastic thanks for the video, there is a few different test case here that will keep me busy a bit. For one two freeform block should not be allowed to be on the same voxel, but it seems that it is still letting you validate the shape. It seems that popup of ghost block is already fixed though. Will keep you posted, thanks.

**Comment by tsunamayo** [comment] 2018-02-09 04:39
Okay I think there should not be any issues but I will wait for your confirmation as I was not able to reproduce most bugs.  Also you will have to resolve existing conflict by hand (when two freeform are overlapping the same voxel - this should be properly prohibited now), for that just edit the form, if it is red right away there is a conflict somewhere. Build coming soon...

**Comment by JRL101** [comment] 2018-02-09 12:56
I'll keep an eye out for the bug as i play too.

**Comment by Senakysam** [comment] 2018-02-13 13:07
Went back and fixed the freeform so that they don't overlap the same voxel, so now they are painted correctly.

**Comment by CyaNox** [comment] 2018-02-27 14:52
Closing since this seems to be fixed.

**Closed by CyaNox** 2018-02-27 14:52 UTC
Labels: Bug
