### ISSUE TITLE
Laser Sensor works?

### ISSUE THREAD

**Issue by TebitoSan** [tsunamayo/Skywanderers#378] opened 2017-11-05 20:45 UTC
My laser sensor doesn't react to switch inputs, nor does anything wired out of it react when I pass through

https://i.gyazo.com/ac1cecd099620da0596e3369f4675792.jpg

**Comment by CyaNox** [comment] 2017-11-05 21:00
Duplicate of #319.

**Closed by CyaNox** 2017-11-05 21:00 UTC
Labels: Duplicate
