### ISSUE TITLE
[18w13b] Custom paint chunk problem

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#707] opened 2018-04-09 21:13 UTC
Here's a gif of the issue:
https://i.imgur.com/9p5Ra2S.gifv
As you can see, when placing blocks that are painted in Custom Colour #1, the entire chunk suddenly updates in the default custom colour, even when it was been set to the white you see me placing blocks in.
It should be noted that the panel is mounted on a block sized rotator

Here's the ship blueprint too:
[BattleCruiser Current.zip](https://github.com/tsunamayo/Skywanderers/files/1891877/BattleCruiser.Current.zip)

**Comment by Vicomt** [comment] 2018-04-10 15:53
this might be a duplicate of https://github.com/tsunamayo/Skywanderers/issues/575

**Closed** 2018-04-11 06:35 UTC
Labels: Bug
