### ISSUE TITLE
Options menu overlaps pause menu

### ISSUE THREAD

**Issue by vetranofwar** [tsunamayo/Skywanderers#195] opened 2017-10-25 18:08 UTC
![20171025130608_1](https://user-images.githubusercontent.com/33100936/32015080-a1b7e570-b985-11e7-9749-fbb19ea82999.jpg)
![20171025130559_1](https://user-images.githubusercontent.com/33100936/32015085-a4af2392-b985-11e7-906d-fc5706421963.jpg)

**Comment by ike709** [comment] 2017-10-25 18:10
Dupe of #170

**Comment by tsunamayo** [comment] 2017-10-25 23:34
This issue have been fixed - it will be up in the next patch. Thanks!

**Closed by tsunamayo** 2017-10-25 23:34 UTC
Labels: bug
