### ISSUE TITLE
[Bug] Framerate and loading issue

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#558] opened 2018-02-27 18:00 UTC
Hello!

I've been facing an issue since yesterday and I don't understand what's going on.
I've made a clean install of Windows on my computer yesterday and ever since I did it, Skywanderers is acting weirdly as you can see in this video (bad framerate, issues loading the ring and, at the end, weird structure):

https://www.youtube.com/watch?v=Gzc-y--e6xI

The framerate I have in the video is what I have in-game, there is no recording issue. I usually have 130-150fps when the game is working as intended.
If I'm leaving the game in the background and open certain type of videos/links/programs, the game crashes giving this error log.

[error.log](https://github.com/tsunamayo/Skywanderers/files/1764101/error.log)

What I tried:
- My drivers are up-to-date.
- Clearing the Save-Data folders doesn't change anything. 
- Reinstalling the game doesn't change anything.

I'm probably missing something but can't get my hand on it. Other games like Rocket League or Dark Souls 3 aren't affected so I thought maybe it did come from an issue with Unity?

**Comment by CyaNox** [comment] 2018-02-27 18:43
I think you may be missing some dependencies and may be a duplicate of:

In #317 I found that there is a dependency lacking for the MSVC Runtime 2015 as per: https://github.com/tsunamayo/Skywanderers/issues/317#issuecomment-344861361

If you have this issue again you can try downloading and installing it from https://www.microsoft.com/en-gb/download/details.aspx?id=48145 and see if that helps.

**Comment by Name11ess** [comment] 2018-02-27 19:27
Seems like that was it, thank you very much CyaNox!

**Comment by CyaNox** [comment] 2018-02-27 19:41
My pleasure.

**Closed by CyaNox** 2018-02-27 19:41 UTC
