### ISSUE TITLE
Copy/pasting child brick entity

### ISSUE THREAD

**Issue by Centauri2442** [tsunamayo/Skywanderers#451] opened 2017-11-17 01:20 UTC
I just copy/pasted a 8x2 child entity that had 2 hinges on it, to another child entity that was a child entity of a few other creations, and when pasting it using the entity unit, it kept on pasting itself on the end of the previous entity that was pasted in, going on infinitely. When saving and then re-logging, both the original pasted entity and the infinitely spawning ones that were being placed after it were all gone. (I'm sorry that this is a bit weird, but it is hard to explain)

EDIT : It appears that it is an issue with spawning an entity onto the same blueprint, therefore updating itself indefinitely

**Comment by CyaNox** [comment] 2017-11-17 03:46
This is likely a duplicate of #374.

**Comment by tsunamayo** [comment] 2017-12-03 12:22
I am unable to reproduce the issue, if you have a blue print with the procedure to follow in order to reproduce that would be of a great help. Thanks!

**Comment by tsunamayo** [comment] 2019-07-29 00:51
No longer applicable. Thanks

**Closed by tsunamayo** 2019-07-29 00:51 UTC
Labels: Bug
