### ISSUE TITLE
[EXPERIMENTAL] Painting a modified FFB may sometimes create new FFB

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#665] opened 2018-03-28 10:51 UTC
https://puu.sh/zRe2S/68d63cc6f2.gif

Might be an edge-case, can supply the BP on request.

**Comment by tsunamayo** [comment] 2018-03-28 11:00
Ah nice yes I would like to see the blueprint as this was reported but I am unable to reproduce. Thanks!

**Comment by Napther** [comment] 2018-03-28 21:44
Here are 2 variations on the same BP. Painting across the bricks to the edge of the retrothruster should spawn the new block. Tested it just now after doing some retooling and still spawning the block.

[Chieftain BPs DEBUG FFB Paint.zip](https://github.com/tsunamayo/Skywanderers/files/1857879/Chieftain.BPs.DEBUG.FFB.Paint.zip)

**Comment by tsunamayo** [comment] 2018-03-29 08:33
Okay finally got rid of this one, fix will be in next update. Cheers!

**Closed by tsunamayo** 2018-03-29 08:33 UTC
Labels: Bug
