### ISSUE TITLE
Memory leak introduced in 17w47a

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#462] opened 2017-11-20 11:16 UTC
This new update has introduced a memory leak.

I've not been able to pinpoint what is causing the leak as neither the log nor any changes to the world seem to affect it.

The memory leak even happens on a newly created world so is not an artifact of anything weird I'm doing to the logic system or my other builds.

On my system the memory leak is roughly 1 Megabyte per second.

**Comment by CyaNox** [comment] 2017-11-20 11:16
The log for reference (Nothing useful can be seen as far as I'm aware in there) [output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1487384/output_log.txt)

**Comment by tsunamayo** [comment] 2017-11-20 11:35
Yes I was not really sure I think I noticed it also, the problem is I upgraded Unity to 2017.3 from 5.6. I will check whether it is coming from the code, I hope it is not the new Unity version ...

**Comment by Xerma** [comment] 2017-11-21 06:05
Was just on my way to report this :P Lost all progress on my Invisible Hand build from this. I messed up a part so I get to fix it now lol

**Comment by Xerma** [comment] 2017-11-21 08:00
Reinstalling seems to fix the issue for now

**Comment by CyaNox** [comment] 2017-11-21 10:41
@Xerma I tried reinstalling and it did not change anything for me. Are there any additional steps you took with reinstalling the game?

**Comment by tsunamayo** [comment] 2017-11-21 11:48
Hi, so I was finally able to pinpoint the faulty API that was doing that, it is now fixed. For some reason the new Unity version doesnt like adding the same commander buffer at two different stage of the pipeline, it was causing a massive leak. I am pushing a new build as it was a nasty issue. Thanks!

**Comment by tsunamayo** [comment] 2017-11-21 12:04
New version is up now, thanks for your help, and sorry for the bug!

**Closed by tsunamayo** 2017-11-21 12:04 UTC
Labels: Bug, High

**Comment by CyaNox** [comment] 2017-11-21 12:16
Can confirm 17w47a2 has fixed this.

(As a side note the initial startup in since the move to the new Unity went from ~1GB memory to under 700MB so an improvement!)
