### ISSUE TITLE
Issues with child/grandchild structures, and pilot seats

### ISSUE THREAD

**Issue by Mantis2k19** [tsunamayo/Skywanderers#1390] opened 2019-07-24 15:09 UTC
### Short Description of the issue:
Issue with child/grandchild :
Cannot place normal windows, power generators or engines on grandchild structures (slider on a slider, etc). Canopy set works, but normal windows do not.

Issue with pilot seats:
Pilot seats seem to shift off the grid when elevated by .25, or placed on a child structure. The direction of offset does not seem consistent.
...

### Steps to reproduce the issue:
Issue 1) place a movement piece on a movement piece, attempt to place a window, generator, or engine (no picture available)
...
Issue 2: place a pilot seat, place a movement piece or .25 brick behind it, place another pilot seat on top (picture below shows offset using 0.25m brick)
### Environment
- Skywanderers version: current
- Graphics Card: NVIDIA GTX 650
![20190721162720_1](https://user-images.githubusercontent.com/53107501/61805224-0548ce00-ae68-11e9-8dce-bd512183be64.jpg)
![20190721162715_1](https://user-images.githubusercontent.com/53107501/61805236-0a0d8200-ae68-11e9-8eed-f1eaeab4d52a.jpg)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment] 2019-07-25 05:51
Hi, the first isssue is not an issue, it is by design as spawning a new grid is a bit problematic with smaller mechanism. The second is fixed and will be released for 19w30a. Thanks!

**Closed by tsunamayo** 2019-07-25 05:51 UTC
Labels: Bug
