### ISSUE TITLE
[Bug] Window Tile Wedge axis

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1658] opened 2020-03-17 21:00 UTC
### Short Description of the issue:
The Window Tile Wedge brick has an incorrectly aligned axis, making it awkward to place in some situations

Here's a regular Wedge
![image](https://user-images.githubusercontent.com/27857711/76900715-cc93b400-6891-11ea-9b04-5dc1a24c1289.png)

Here's the Window Wedge
![image](https://user-images.githubusercontent.com/27857711/76900645-a9690480-6891-11ea-8980-d8fb8f071db8.png)
Notice that the axis used to place it is 25cm off to the right

### Steps to reproduce the issue:
Stretch a Window Tile Wedge brick and notice the axis, then compare it with a regular Wedge
...

The new Window Tile Triangle works perfectly, the offset on it makes it very useful. Thanks for slimming down the Window Tile to match as well, although I'd have preferred it stay at a 25cm cube size to make it more versatile. For now I think the only major window shape we're missing is a hepta.

### Environment
- Skywanderers version: 20w12a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment] 2020-03-17 23:35
Hum it is not really a bug, the axis start at the center of the block, not the side...
But I can see why you dont like it, the length is smaller because of that, I will see if I can update my logic.
Also with the new thickness having a 0.25 dont make sense, it is just a full non transparent block...
I had to make it bigger for the stretching tech.
Thanks

**Comment by ProPeach** [comment] 2020-03-17 23:55
Ah interesting, I see.
The main reason I reported it is that it seems to make stretching it onto an existing shape more difficult, as the shape will always try to stretch 0.25cm wider than it should meaning it clips so you can't place it. I assumed the axis was to blame for that as it's the only thing I could see different about the window wedge vs the regular wedge

**Comment by tsunamayo** [comment] 2020-03-17 23:59
Okay now I think I didnt really understood the issue. It is not just about the white line display?

**Comment by ProPeach** [comment] 2020-03-18 00:03
When you stretch the window wedge, it feels like the point you're stretching is actually 25cm inside the wedge collision model. So if you stretch it from bottom right to top left in the picture I uploaded, the model will clip 25cm into the vertical face on the left so the shape turns red and you can't place it. I guessed that was caused by the difference in the white axis line, but by the sounds of it that might not be the cause.

**Comment by tsunamayo** [comment] 2020-03-18 01:45
Hum okay I think I got it. Indeed the placement is in the middle of the brick...

**Comment by tsunamayo** [comment] 2020-03-29 04:23
Okay I added a small offset, so the placement feels more logical. Will be in 20w14a. Thanks!

**Comment by ProPeach** [comment] 2020-04-03 14:37
Hello again, sadly this one persist and I can't seem to reopen the issue myself.
When stretching this brick, it still misses the edge you're pointing at and attempts to place inside the brick itself, rather than snapping to the edge like all other bricks do. I'm not sure what's unique about this brick to make it do this, although it does still seem that the placement is in the middle of the brick.
![image](https://user-images.githubusercontent.com/27857711/78372052-b50e3800-75c0-11ea-89d4-0decb648c89f.png)

**Comment by ProPeach** [comment] 2020-04-03 14:40
Actually, it looks like the Window Tile also has the same placement bug. The Triangle and Tetra are fine though
![image](https://user-images.githubusercontent.com/27857711/78372691-7f1d8380-75c1-11ea-8972-2f4abab120ca.png)

**Comment by tsunamayo** [comment] 2020-04-08 04:17
Issue re-opened.

**Comment by tsunamayo** [comment] 2020-04-08 04:26
I cant reproduce the issue, it works fine on my side... Could you send me a blueprint, or a video if it is not too complicated on your side? 
To confirm you are using the bridge feature, aka you point two points that are not coplanar to create a 3d scale without clicking on the rotate button (like you need to do for a vertical stretch)
Thanks

**Comment by ProPeach** [comment] 2020-04-08 12:56
Thanks for reopening the issue, in the future would you prefer I made a new thread or asked for an issue to reopen like this one?

Here's a video of what I'm talking about. I compare the placement rules of the regular bricks and their canopy counterparts, I'm assuming that they should behave similarly.
https://i.imgur.com/4ybKUd6.mp4

**Comment by tsunamayo** [comment] 2020-04-13 06:14
Perfect! I cant reproduce the issue, I keep you posted. Yes maybe next time its better to open a new one, so that it dont get burried like this one did a little bit... but no big deal really.

**Comment by tsunamayo** [comment] 2020-04-15 00:37
Issue is not fixed - thanks a lot for spotting that one, video was super usefull! Will be in 20w16b. Cheers

**Closed by tsunamayo** 2020-04-15 00:37 UTC
Labels: Bug, To Fix / To Do
