### ISSUE TITLE
Pressing F1 won't save the game sometimes [Experimental]

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#675] opened 2018-03-30 01:53 UTC
After the recent 5mb patch, I loaded a ship into my world, saved, then restarted because the lighting wasn't loading inside the ship. After restarting, the ship wasn't in the world and I was in the position I loaded in at after I had downloaded the update and launched the game for the first time.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1862446/output_log.txt)

**Comment by schlid** [comment] 2018-03-30 02:52
Renaming this blueprint didn't make the save icon appear either.

**Comment by tsunamayo** [comment] 2018-03-30 03:17
Okay is this something you reproduce with all ship? Like if you paint the banshee and reload, was it changed? Thanks

**Comment by schlid** [comment] 2018-03-30 03:22
I'm about to sleep, I'll confirm this tomorrow. Thanks for responding.

**Comment by tsunamayo** [comment] 2018-03-30 04:38
Thanks, sure no pb! I am asking because I can load your ship, do some painting, save, and then everything is fine on reload.

**Comment by schlid** [comment] 2018-03-30 17:05
I've been unable to replicate this since yesterday. I've tried about 10 different ships and all save fine now including the sephi. Damn :L

**Comment by BrickMacklin** [comment] 2018-03-31 08:55
This has been happening to me in all my saves.

**Comment by Napther** [comment] 2018-03-31 21:32
More info in #679 

Any ship spawned via BP block deletes/wipes each reload of the game/world which I believe is the current issue

**Comment by tsunamayo** [comment] 2018-04-01 01:40
This bug should be fixed - as I suspect it is the same issue as #679. Thanks

**Closed by tsunamayo** 2018-04-01 01:40 UTC
