### ISSUE TITLE
[Experimental] Can't place symmetry blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#382] opened 2017-11-05 23:56 UTC
I opened my game, flew to a new section to work on a new idea, placed a starter block then one hull and thus couldn't place a symmetry block on the starter block nor the hull block.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1444583/output_log.txt)

**Comment by CyaNox** [comment] 2017-11-06 00:00
Duplicate of #376.

**Closed by CyaNox** 2017-11-06 00:00 UTC
Labels: Duplicate

**Comment by tsunamayo** [comment] 2017-11-06 00:07
Thanks indeed, issue was just fixed. Cheers
