### ISSUE TITLE
Ver 17w45a2 - Problem with Rails

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Skywanderers#401] opened 2017-11-07 21:36 UTC
Hey Tsuna, Have been having an issue with rails since yesterdays patch, 

1st Problem.  I cannot place rails on Bricks only on blocks, before the patch i have managed to add small rails to bricks.

2nd Problem.  The game refuses to let me place stud panels or flat stud panels on to rails. have tryed all sizes from 1x1 to 4x4, I get no placement ghost on the rail slider.

have done the usual, uninstall/re-install  the but problem persists through out.

**Comment by MrBester** [comment] 2017-11-07 22:20
Not sure it is a duplicate of #391, I can place stud panels fine, just not on the rail sliders.

**Comment by CyaNox** [comment] 2017-11-07 22:44
Indeed I am not sure either else I would have closed this already ;-) We'll have to await the analysis of our master designer Tsunamayo!

**Comment by tsunamayo** [comment] 2017-11-07 23:18
Thanks, it was indeed a duplicate of #391 ;-)! Fix will be in next build. Cheers

**Closed by tsunamayo** 2017-11-07 23:18 UTC
Labels: Duplicate
