### ISSUE TITLE
Docking Probes Can't Be Placed On Child Entities

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Skywanderers#482] opened 2017-11-24 04:35 UTC
I'm not sure that this is a bug, but I know that it is making some building designs I would like to achieve impossible without the ability to place a docking probe on a slider/rotator. 

Otherwise building certain things would be possible if it were possible to activate the docking sequence via activating only the docking cone.

I'm not sure this is a bug or if it is a planned thing. But it would be very useful if it were changed.

**Comment by CyaNox** [comment] 2017-11-24 15:28
Duplicate of #405.

**Closed** 2017-11-30 04:01 UTC
Labels: Duplicate
