### ISSUE TITLE
[19w29b] Linking block slider to indicator light causes slider body to disappear, freezes nearby sliders

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1391] opened 2019-07-28 02:28 UTC
### Issue:
I linked a block slider/large slider to an indicator light, and found the slider body had vanished, leaving the slider head and everything built on it floating. The head could not be deleted.

### Steps to reproduce the issue:

- Build a block slider of any length
- build brick/block sliders next to/nearby it
- Link the block slider to an indicator light
- attempt to activate any of the other sliders (either by hand or with logic)

### Environment
- Skywanderers version: 19w29b
- Graphics Card: Nvidia GeForce GTX 1060 6gb

###Additional information
This is the first time I have tried linking a slider/rotor/hinge to an indicator light in the past couple of versions, and the first using the new sliders/hinges.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3438791/output_log.txt)

**Comment by tsunamayo** [comment] 2019-07-29 00:15
Hi, I am pretty sure it should be the same bug as #1383 as I cant reproduce it. It should be fixed in upcoming 19w31a. Cheers!

**Closed by tsunamayo** 2019-07-29 00:15 UTC
Labels: Bug
