### ISSUE TITLE
All ships/entities are moving downwards at a very slow rate. (Experimental)

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#659] opened 2018-03-27 18:06 UTC
When spawning a ship, it will glide incredibly slowly downwards instead of stay still. Entering the joystick doesn't fix this, flying and stopping doesn't fix this either. 

It moves at an incredibly slow rate but it's very annoying when doing small building work as even if you're aligned to the object, it still moves away from you, and I can imagine for some it may be quite nauseating.

**Comment by tsunamayo** [comment] 2018-03-28 01:27
Weird indeed, I will have a look at this. Thanks

**Comment by tsunamayo** [comment] 2018-04-12 03:46
Hi @schlid, it seems I cant reproduce the issue this time (in both experimental and main), could you please tell me if you still see teh bug? Thanks

**Comment by schlid** [comment] 2018-04-17 01:43
![image](https://user-images.githubusercontent.com/31857052/38843858-db31a46c-41e8-11e8-9fa5-5d3342784f3f.png)
Picture above taken 30 seconds before the one below. On latest experimental build as of time of posting this.
![image](https://user-images.githubusercontent.com/31857052/38843896-04f754ae-41e9-11e8-8539-afb37613d7b3.png)

If you look closely you can see the blocks slightly lower in the second image

**Comment by tsunamayo** [comment] 2020-03-18 23:35
I think this should be fixed in current versions. Thanks

**Closed by tsunamayo** 2020-03-18 23:35 UTC
Labels: Bug
