### ISSUE TITLE
Bloom effects the toolbar

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#454] opened 2017-11-19 02:35 UTC
This has been an issue since pre pre alpha however its not been fixed yet. This can be particularly frustrating when building engines.
![image](https://user-images.githubusercontent.com/31857052/32986811-fd763876-ccd1-11e7-971f-a6565ea30c2d.png)
Also if we could toggle bloom that would be incredibly helpful.

**Comment by tsunamayo** [comment] 2017-11-20 08:49
Hi, yes it is painful. I might remove the bloom, but it is a bit harder to do than it sounds. 
What I will do for sure is to have block that change their glowing intensity depending on their state, so an engine not working would no longer be destroying your eyes. Also I might kill the player one day when you are getting too close to a working engine ;-) Fix will have to wait a fit unfortunately ...

**Comment by AfterRebelion** [comment] 2019-06-06 15:58
Duplicate of https://github.com/tsunamayo/Skywanderers/issues/123

**Closed** 2019-06-06 23:21 UTC
Labels: Enhancement, Suggestion
